# TODO: improve this later

FROM node:20-alpine AS builder
WORKDIR /app

COPY . .

ARG NEXT_PUBLIC_URL
ARG NEXT_PUBLIC_PB_URL
ARG NEXT_PUBLIC_UMAMI_SCRIPT
ARG NEXT_PUBLIC_UMAMI_ID
ARG PB_USERNAME
ARG PB_PASSWORD
ARG CLEAR_CACHE_KEY

ENV NEXT_PUBLIC_URL=$NEXT_PUBLIC_URL
ENV NEXT_PUBLIC_PB_URL=$NEXT_PUBLIC_PB_URL
ENV NEXT_PUBLIC_UMAMI_SCRIPT=$NEXT_PUBLIC_UMAMI_SCRIPT
ENV NEXT_PUBLIC_UMAMI_ID=$NEXT_PUBLIC_UMAMI_ID
ENV PB_USERNAME=$PB_USERNAME
ENV PB_PASSWORD=$PB_PASSWORD
ENV CLEAR_CACHE_KEY=$CLEAR_CACHE_KEY

RUN npm install

ENV NODE_ENV=production

RUN npm run build

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["npm", "start"]