FROM oven/bun:latest AS builder

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install

COPY . .

ENV NODE_ENV=production
RUN bun run build

FROM oven/bun:latest AS runner

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ARG NEXT_PUBLIC_URL
ARG NEXT_PUBLIC_PB_URL
ARG NEXT_PUBLIC_UMAMI_SCRIPT
ARG NEXT_PUBLIC_UMAMI_ID
ARG PB_USERNAME
ARG PB_PASSWORD
ARG CLEAR_CACHE_KEY

ENV NEXT_PUBLIC_URL=$NEXT_PUBLIC_URL
ENV NEXT_PUBLIC_PB_URL=$NEXT_PUBLIC_PB_URL
ENV NEXT_PUBLIC_UMAMI_SCRIPT=$NEXT_PUBLIC_UMAMI_SCRIPT
ENV NEXT_PUBLIC_UMAMI_ID=$NEXT_PUBLIC_UMAMI_ID
ENV PB_USERNAME=$PB_USERNAME
ENV PB_PASSWORD=$PB_PASSWORD
ENV CLEAR_CACHE_KEY=$CLEAR_CACHE_KEY

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

COPY --from=builder /app ./

EXPOSE 3000

CMD ["bun", "run", "start"]